[project]
name = "ticktick-airbyte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "airbyte-cdk>=6.60.7",
    "dida365>=0.1.9",
]
